### ISSUE TITLE
Initial Penalty

### ISSUE THREAD

**Issue by nalepae** [benjaminion/upgrading-ethereum-book#11]
https://eth2book.info/bellatrix/part2/incentives/slashing

> The offender immediately has one **sixty-fourth** ([MIN_SLASHING_PENALTY_QUOTIENT_BELLATRIX](https://eth2book.info/bellatrix/part3/config/preset#min_slashing_penalty_quotient)) of its effective balance deducted from its actual balance. This is a maximum of 1 ETH due to the cap on effective balance.

Should "one **sixty-fourth**" be replaced by `1/32`?

**Comment by benjaminion** [comment]
Yep, quite correct. Thank you!

Fixed upstream - it will get updated when I next publish an update.
