### ISSUE TITLE
Typo in part2/building_blocks/signatures/#aggregating-signatures

### ISSUE THREAD

**Issue by flanagansteve** [benjaminion/upgrading-ethereum-book#16]
You say:

> The exact operations are not like normal the addition of numbers that we are familiar with, but the operation is completely analogous.

but you likely swapped "normal the" and meant:

> The exact operations are not like the normal addition of numbers that we are familiar with, but the operation is completely analogous.

**Comment by benjaminion** [comment]
Thank you! I've fixed it upstream and it will make its way into a release in the next few days :pray:
