### ISSUE TITLE
Sync Committee rewards should be part of the block processing mention (?)

### ISSUE THREAD

**Issue by lucassaldanha** [benjaminion/upgrading-ethereum-book#17]
When talking about [Rewards and Penalties](https://eth2book.info/bellatrix/part3/transition/epoch/#process-rewards-and-penalties) you say that following:

> For reference, the only other places where rewards and penalties are applied are as follows:
> during epoch processing: for [sync committee participation](https://eth2book.info/bellatrix/part3/transition/block#def_process_sync_aggregate), and applying [extended slashing penalties](https://eth2book.info/bellatrix/part3/transition/epoch#def_process_slashings).
> during block processing: when applying the [proposer reward](https://eth2book.info/bellatrix/part3/transition/block#def_process_attestation), and initial [slashing rewards and penalties](https://eth2book.info/bellatrix/part3/helper/mutators#def_slash_validator).

However, based on the spec my understanding is that sync_committee rewards are applied as part of the block processing, not only at epoch boundaries.

Maybe I misunderstood something. But I thought I'd open this ticket here in any case :)

Reference: https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/beacon-chain.md#block-processing

**Comment by benjaminion** [comment]
Nice one, thanks! Don't know what I was thinking there. I've fixed it upstream. Hoping to do a big round of publishing later today, and then it will be in the live version.
