### ISSUE TITLE
Fix some typos

### ISSUE THREAD

**Issue by chong-he** [benjaminion/upgrading-ethereum-book#18]
1. On pg. 13, under Section `Block Trees`, second point:
> ..., or to censor some transaction in B

Suggestion:
> ..., or to censor some transactions in B

2. Pg. 16, top paragraph, I am thinking that "assume" is a better word than "imagine". When I first read through the sentence I didn't get it completely, but I would get the meaning straightaway if the wording used is "assume". This is only a suggestion though, feel free to ignore.

3. Pg. 18, footnote 7 is not seen

4. Pg. 24, under Section `LMD`:
> In our proof of stake

Suggestion:
> In proof of stake

Also:
> and the fork choice chooses based on the whatever attestation ...

Suggestion
> and the fork choice chooses based on whatever attestation ...

Thank you.

**Comment by benjaminion** [comment]
Thank you very much - this is helpful. Apologies for taking a while to get to this, I have been away.

1. Not changed, I'm ok with "some transaction".
2. Changed to "assume".
3. This is weird. I've added it to the PDF readme doc as a known issue. The PDF is still experimental, so I'll look into it at some point, but it's not high priority right now.
4. I added "protocol", but left "our proof of stake" - the point is that there are many different ways that you can do PoS; we have chosen a particular version of PoS for Ethereum.
5. Fixed. Thanks.

I've made the changes upstream; they will get pushed here when I next publish an update, maybe in a week or so.

Thanks again.
