### ISSUE TITLE
Print Styles

### ISSUE THREAD

**Issue by NiloCK** [benjaminion/upgrading-ethereum-book#2]
Printing from the website is not functional - produces a single page that includes the table of contents, an amount body text that happens to fit on that page, and nothing else. The body text even disappears off the right-hand margin.

Basic desirables for a print style are:
- remove left-hand ToC and right-hand chapter navigation sidebars
- remove navigation links (Back, Next)
- check on things like mid image or table page breaks
- ... including the body text in full

Requires specific thought:
- link styling to print URLs (this is usually a nice thing to do w/ relative links, but not so nice with long / ugly links)

![image](https://user-images.githubusercontent.com/10780590/149162369-d4cb0a58-7ffd-4b41-b8d7-38a8ea42ac53.png)

**Comment by benjaminion** [comment]
Yep, totally. I was actually thinking about this a couple of hours ago while out and about and put it at the top of my mental backlog. I'll work on an initial print stylesheet in the next few days as something to iterate on.

**Comment by NiloCK** [comment]
Happy to hear it. I raise this issue lots of places to mixed response.

If this remains untouched for a while I could take a crack at it, or you could assign me if you like with the understanding that it's on a ~2 weeksish timetable.

**Comment by benjaminion** [comment]
Thanks! I've just done a [super-simple update](https://github.com/benjaminion/upgrading-ethereum-book/commit/f90fa6f2e46e9ed2bf62c768693e6b674598fc82) that mostly just turns things off. It's not beautiful, but is waaay better than before - actually functional!

Happy to iterate on this, but hopefully that helps for now.
