### ISSUE TITLE
2.3.1 Missing word / wording

### ISSUE THREAD

**Issue by rocknet** [benjaminion/upgrading-ethereum-book#21]
Sixth para in 2.3.1 Finality section

> Finality in Ethereum's consensus layer is delivered by the Casper FFG mechanism that we'll exploring soon.

Suggest "we'll be exploring"... or "we'll explore"

**Comment by benjaminion** [comment]
Perfect, thank you! I've fixed it upstream and it will go live when I next publish an update.
