### ISSUE TITLE
Small typo in reference name

### ISSUE THREAD

**Issue by upavloff** [benjaminion/upgrading-ethereum-book#25]
Small typo [here](https://github.com/benjaminion/upgrading-ethereum-book/blob/d22d2bfeb0e95881e7f06ce339a272703b8c6807/src/book.md?plain=1#L11343).

```[`def_process_rewards_and_penalties()`](#def_process_rewards_and_penalties) |```
instead of:
```[`process_rewards_and_penalties()`](#def_process_rewards_and_penalties) |```

**Comment by benjaminion** [comment]
Thank you! I've made the fix upstream - will go live next time I publish an update.
