### ISSUE TITLE
Update VALIDATOR_REGISTRY_LIMIT subsection

### ISSUE THREAD

**Issue by chong-he** [benjaminion/upgrading-ethereum-book#26]
In [`VALIDATOR_REGISTRY_LIMIT`](https://eth2book.info/capella/part3/config/preset/#validator_registry_limit), the sentence:

> This is largely because there is nowhere yet to send a validator's remaining deposit and staking rewards, so they continue to need to be tracked in the beacon chain.

can be updated, as currently deposit and rewards will be sent to the withdrawal address after the Capella upgrade. 
(not sure the original `to need to be tracked` is intentional or typo, I remove the `to need` in the suggestion below)

My suggestion is to remove the first part of the sentence, since the subsection does not really talk about deposits and rewards. So the paragraph can be:

> In the current design, validators are never removed from this list, even after exiting from being a validator. They continue to be tracked in the beacon chain. 

 Of course, feel free to accept, modify or ignore. Thank you

**Comment by benjaminion** [comment]
Many thanks! I've adopted your suggestion, and added a link to [EIP-6914](https://eips.ethereum.org/EIPS/eip-6914) as it is relevant here, I think.

Fixes are upstream and I'll publish them at some point.

Thanks again.
