### ISSUE TITLE
Typo in "Validator Top-ups" section of Deposit Processing page

### ISSUE THREAD

**Issue by flanagansteve** [benjaminion/upgrading-ethereum-book#27]
In the ["Validator Top-ups" section of Deposit Processing page](https://eth2book.info/capella/part2/deposits-withdrawals/deposit-processing/#validator-top-ups), you say:

"Not many top-ups have been performed to date, but there are a some [examples](https://etherscan.io/tx/0x3e68702566edee0061344eb99c484b4fac8800db082980bb6027d1dca09f5812)."

I believe the "a" between "there are" and "some" is extraneous; you likely want:

"Not many top-ups have been performed to date, but there are some [examples](https://etherscan.io/tx/0x3e68702566edee0061344eb99c484b4fac8800db082980bb6027d1dca09f5812)."

**Comment by benjaminion** [comment]
Thanks for reporting! I actually fixed this one [a while back](https://github.com/benjaminion/upgrading-ethereum-book/commit/889e5d06372e532679449f46134ee2dcf64e20ba) but seems like I haven't published a new version to the website since then. My apologies. Will update soonish.
