### ISSUE TITLE
Very helpful information! Please update it!

### ISSUE THREAD

**Issue by LuozhuZhang** [benjaminion/upgrading-ethereum-book#7]
Especially the part about the [consensus protocol](https://eth2book.info/altair/part2/consensus), it's a pity we can't see the author's understanding of [Casper](https://eth2book.info/altair/part2/consensus/casper_ffg) and [LMD-GHOST](https://eth2book.info/altair/part2/consensus/lmd_ghost).

**Comment by benjaminion** [comment]
It's coming!

I'm currently updating everything to account for the Merge. The next priority is then the chapter on consensus including Casper and LMD-GHOST (it's already underway, but interrupted by the Merge).

**Comment by LuozhuZhang** [comment]
> It's coming!
> 
> I'm currently updating everything to account for the Merge. The next priority is then the chapter on consensus including Casper and LMD-GHOST (it's already underway, but interrupted by the Merge).

👍

**Comment by benjaminion** [comment]
I've just published an update for the Bellatrix fork 🎉 

As above, Consensus is the next big target.

Closing this now as it's constantly a work in progress, and will be for the next year or more.
