### ISSUE TITLE
Mistakes 2.8.3. Issuance section

### ISSUE THREAD

**Issue by BornaBM** [benjaminion/upgrading-ethereum-book#9]
First of all, amazing work! Your online guide has been of great help to me, I have also left you a DM on Twitter to introduce myself and ask some other things as well. I would really appreciate if you take a look at that! My twitter @Borna48052966

While reading section 2.8.3. I believe that there are a few mistakes
- In the formula for BASE_REWARD there is BASE_REWARD_PER_EPOCH component missing (should have value of 4 I believe)
- Further when you are explaining that certain validator's earnings per epoch can be easily calculated (assuming that validator's effective balance is 32) as 32*b. But b (BASE_REWARD) already has inside the formula effective balance, so you are basically multiplying it twice.

Kind regards,
Borna

**Comment by benjaminion** [comment]
Hi Borna,

I appreciate the feedback and interest!

> In the formula for BASE_REWARD there is BASE_REWARD_PER_EPOCH component
missing (should have value of 4 I believe)

Could you be more specific about where the error is? As far as I can see
there is no constant BASE_REWARD_PER_EPOCH in any of the specs.

> But b (BASE_REWARD) already has inside the formula effective balance, so
you are basically multiplying it twice.

Since the Altair spec
<https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/beacon-chain.md>,
what I call `b` in section 2.8.3 is the "base reward per increment". An
increment is 1 ETH of effective balance. So if a validator has 32 ETH
effective balance then its base reward (per epoch) is `32b`. If you
disagree, again could you be more specific about where the error is.

> I have also left you a DM on Twitter

Thanks! Twitter is a bit inconsistent about notifying me of DMs. I'll take
a run at your Stack Exchange question in a little while.

Ben

**Comment by BornaBM** [comment]
Thanks for quick response!

1. Regarding the first issue, please take a look here: https://ethereum.org/uk/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/
You will see that there is `base_rewards_per_epoch` component in the equation. Maybe the GitHub is outdated? The documentation on the link has been updated last time a month ago.

2. It seems that base_reward formula on the Ethereum website and the one on the GitHub (that you are using) have a slight variation, but I am not sure if that might cause problems when calculating other rewards. To elaborate further - on the same link I pasted above you will see that they are immediately accounting for the whole validator's effective balance in the formula for base_reward. Your equation for base_reward doesn't account for the whole amount. At first I thought that your "base_reward_per_increment" is just the effective balance in increments of 1 ETH, but now from your response it seems that it is just 1 ETH. If that "base_reward_per_increment" is only 1 ETH always in the equation, then is there even any point of putting it there?

Nonetheless, I still have to check thoroughly your section 2.8.4. (thus I could be wrong) and compare to Ethereum documentation for calculating rewards. Maybe all of the equations for deriving other rewards in your guide from the base_reward are adjusted for that missing effective balance in base_reward formula, so at the end they are being calculated correctly as well. But still I would love to know which formula for base_reward is the "correct" one - one that includes eff. balance or the one that doesn't.

Thank you for your response on Stack Exchange! I will read it and digest it a few more times before I potentially leave a comment just to make sure I understood it correctly :)

Borna

**Comment by benjaminion** [comment]
> You will see that there is base_rewards_per_epoch component in the
equation.

That is outdated. base_rewards_per_epoch was removed from the spec in the
Altair upgrade which changed many of the reward and penalty mechanisms. See
the note here:
https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/beacon-chain.md#get_base_reward

> If that "base_reward_per_increment" is only 1 ETH

base_reward_per_increment is the base reward per 1 ETH of effective
balance. If your effective balance is 20 ETH, then your base reward for the
epoch is 20 * base_reward_per_increment. The "increment" referred to in the
name is 1 ETH. This is a bit weird, but it basically works.

Everything in the currently published edition <https://eth2book.info/altair>
refers to the Altair version of the specification. That was the beacon
chain spec deployed from October 2021 to September 2022 which
comprises the Phase
0
<https://github.com/ethereum/consensus-specs/blob/v1.1.1/specs/phase0/beacon-chain.md>
spec plus the Altair
<https://github.com/ethereum/consensus-specs/blob/v1.1.1/specs/altair/beacon-chain.md>
spec. I'd be happy to receive any fixes for deviations from that spec. I am
in the process of updating to the new Bellatrix
<https://github.com/ethereum/consensus-specs/blob/v1.2.0/specs/bellatrix/beacon-chain.md>
specs in addition, but these do not change any rewards and penalty
calculations.

Ben

**Comment by BornaBM** [comment]
First, I apologize, it seems that I mixed one term in my reply accidentally:

> At first I thought that your "base_reward_per_increment" is just the effective balance in increments of 1 ETH, but now from your response it seems that it is just 1 ETH. If that "base_reward_per_increment" is only 1 ETH always in the equation, then is there even any point of putting it there?

I wrote of `base_reward_per_increment`, while I actually wanted to write the `effective_balance_increment`
(There are two sources, one GitHub and the other is Ethereum Docs and they use similarly named variables.)

What you are saying now makes complete sense. Yes indeed, it seems that now the base_reward is actually base_reward per increment. I guess the Ethereum Docs is outdated then.

Forgive me, but I still don't understand why we still have `effective_balance_increment` in the formula? If it just equal to 1, then anything multiplied by 1 is simply that thing. Just to emphasize that the multiplier (effective balance) is supposed to come? I guess I am still missing some piece?

Borna

**Comment by benjaminion** [comment]
> If it just equal to 1, then anything multiplied by 1 is simply that
thing.

EFFECTIVE_BALANCE_INCREMENT is set to 1,000,000,000 Gwei because balances
are always specified in Gwei, not ETH. For convenience I sometimes say it
is 1 ETH, but that's the same thing.

The ethereum.org site is not authoritative, and is likely out of date. The
only authoritative source for the specs is the Github repo,
https://github.com/ethereum/consensus-specs/.

Ben

**Comment by BornaBM** [comment]
Ah got it, thanks! Wish you a lot of success with finishing the guide!
